version: '3'

services:

  mysql8.0:
    image: mysql:8.0
    container_name: mysql_8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=work
      - MYSQL_USER=worker
      - MYSQL_PASSWORD=worker
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
  redis4:
    image: redis:5-alpine
    container_name: redis_5
    ports:
      - 6379:6379
  localMailServer:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
      - 25:1025
      - 465:1025
      - 587:1025
