/*
 * This file is generated by jOOQ.
 */
package com.example.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 住所
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 980641036;

    private final String prefectureCd;
    private final String prefectureName;
    private final String cityCd;
    private final String cityName;
    private final String townStreetCd;
    private final String townStreetName;
    private final Double latitude;
    private final Double longitude;
    private final String originDocCd;
    private final String townStreetKbnCd;

    public Address(Address value) {
        this.prefectureCd = value.prefectureCd;
        this.prefectureName = value.prefectureName;
        this.cityCd = value.cityCd;
        this.cityName = value.cityName;
        this.townStreetCd = value.townStreetCd;
        this.townStreetName = value.townStreetName;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.originDocCd = value.originDocCd;
        this.townStreetKbnCd = value.townStreetKbnCd;
    }

    public Address(
        String prefectureCd,
        String prefectureName,
        String cityCd,
        String cityName,
        String townStreetCd,
        String townStreetName,
        Double latitude,
        Double longitude,
        String originDocCd,
        String townStreetKbnCd
    ) {
        this.prefectureCd = prefectureCd;
        this.prefectureName = prefectureName;
        this.cityCd = cityCd;
        this.cityName = cityName;
        this.townStreetCd = townStreetCd;
        this.townStreetName = townStreetName;
        this.latitude = latitude;
        this.longitude = longitude;
        this.originDocCd = originDocCd;
        this.townStreetKbnCd = townStreetKbnCd;
    }

    @NotNull
    @Size(max = 2)
    public String getPrefectureCd() {
        return this.prefectureCd;
    }

    @Size(max = 191)
    public String getPrefectureName() {
        return this.prefectureName;
    }

    @NotNull
    @Size(max = 5)
    public String getCityCd() {
        return this.cityCd;
    }

    @Size(max = 191)
    public String getCityName() {
        return this.cityName;
    }

    @NotNull
    @Size(max = 12)
    public String getTownStreetCd() {
        return this.townStreetCd;
    }

    @Size(max = 191)
    public String getTownStreetName() {
        return this.townStreetName;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    @Size(max = 1)
    public String getOriginDocCd() {
        return this.originDocCd;
    }

    @Size(max = 1)
    public String getTownStreetKbnCd() {
        return this.townStreetKbnCd;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(prefectureCd);
        sb.append(", ").append(prefectureName);
        sb.append(", ").append(cityCd);
        sb.append(", ").append(cityName);
        sb.append(", ").append(townStreetCd);
        sb.append(", ").append(townStreetName);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(originDocCd);
        sb.append(", ").append(townStreetKbnCd);

        sb.append(")");
        return sb.toString();
    }
}
