/*
 * This file is generated by jOOQ.
 */
package com.example.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * ユーザ
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 574416176;

    private final ULong         userId;
    private final String        userName;
    private final String        userPassword;
    private final UShort        roleCd;
    private final Boolean       credentialsExpiredFlg;
    private final Boolean       accountExpiredFlg;
    private final Boolean       accountLockedFlg;
    private final Boolean       enabledFlg;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;

    public User(User value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userPassword = value.userPassword;
        this.roleCd = value.roleCd;
        this.credentialsExpiredFlg = value.credentialsExpiredFlg;
        this.accountExpiredFlg = value.accountExpiredFlg;
        this.accountLockedFlg = value.accountLockedFlg;
        this.enabledFlg = value.enabledFlg;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public User(
        ULong         userId,
        String        userName,
        String        userPassword,
        UShort        roleCd,
        Boolean       credentialsExpiredFlg,
        Boolean       accountExpiredFlg,
        Boolean       accountLockedFlg,
        Boolean       enabledFlg,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.roleCd = roleCd;
        this.credentialsExpiredFlg = credentialsExpiredFlg;
        this.accountExpiredFlg = accountExpiredFlg;
        this.accountLockedFlg = accountLockedFlg;
        this.enabledFlg = enabledFlg;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public ULong getUserId() {
        return this.userId;
    }

    @NotNull
    @Size(max = 191)
    public String getUserName() {
        return this.userName;
    }

    @NotNull
    @Size(max = 191)
    public String getUserPassword() {
        return this.userPassword;
    }

    @NotNull
    public UShort getRoleCd() {
        return this.roleCd;
    }

    public Boolean getCredentialsExpiredFlg() {
        return this.credentialsExpiredFlg;
    }

    public Boolean getAccountExpiredFlg() {
        return this.accountExpiredFlg;
    }

    public Boolean getAccountLockedFlg() {
        return this.accountLockedFlg;
    }

    public Boolean getEnabledFlg() {
        return this.enabledFlg;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(roleCd);
        sb.append(", ").append(credentialsExpiredFlg);
        sb.append(", ").append(accountExpiredFlg);
        sb.append(", ").append(accountLockedFlg);
        sb.append(", ").append(enabledFlg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
