/*
 * This file is generated by jOOQ.
 */
package com.example;


import com.example.tables.Address;
import com.example.tables.Prefecture;
import com.example.tables.Role;
import com.example.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>work</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_IDX1 = Indexes0.ADDRESS_IDX1;
    public static final Index ADDRESS_PRIMARY = Indexes0.ADDRESS_PRIMARY;
    public static final Index PREFECTURE_PRIMARY = Indexes0.PREFECTURE_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index ROLE_UQ1 = Indexes0.ROLE_UQ1;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_ROLE_CD = Indexes0.USER_ROLE_CD;
    public static final Index USER_UQ1 = Indexes0.USER_UQ1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADDRESS_IDX1 = Internal.createIndex("idx1", Address.ADDRESS, new OrderField[] { Address.ADDRESS.LATITUDE, Address.ADDRESS.LONGITUDE }, false);
        public static Index ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", Address.ADDRESS, new OrderField[] { Address.ADDRESS.PREFECTURE_CD, Address.ADDRESS.CITY_CD, Address.ADDRESS.TOWN_STREET_CD }, true);
        public static Index PREFECTURE_PRIMARY = Internal.createIndex("PRIMARY", Prefecture.PREFECTURE, new OrderField[] { Prefecture.PREFECTURE.PREFECTURE_CD }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ROLE_CD }, true);
        public static Index ROLE_UQ1 = Internal.createIndex("uq1", Role.ROLE, new OrderField[] { Role.ROLE.ROLE_NAME }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.USER_ID }, true);
        public static Index USER_ROLE_CD = Internal.createIndex("role_cd", User.USER, new OrderField[] { User.USER.ROLE_CD }, false);
        public static Index USER_UQ1 = Internal.createIndex("uq1", User.USER, new OrderField[] { User.USER.USER_NAME }, true);
    }
}
