/*
 * This file is generated by jOOQ.
 */
package com.example.tables.records;


import com.example.tables.Address;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record3;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 住所
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record10<String, String, String, String, String, String, Double, Double, String, String> {

    private static final long serialVersionUID = -1595441943;

    /**
     * Setter for <code>work.address.prefecture_cd</code>. 都道府県コード
     */
    public AddressRecord setPrefectureCd(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>work.address.prefecture_cd</code>. 都道府県コード
     */
    @NotNull
    @Size(max = 2)
    public String getPrefectureCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>work.address.prefecture_name</code>. 都道府県名
     */
    public AddressRecord setPrefectureName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>work.address.prefecture_name</code>. 都道府県名
     */
    @Size(max = 191)
    public String getPrefectureName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>work.address.city_cd</code>. 市区町村コード
     */
    public AddressRecord setCityCd(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>work.address.city_cd</code>. 市区町村コード
     */
    @NotNull
    @Size(max = 5)
    public String getCityCd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>work.address.city_name</code>. 市区町村名
     */
    public AddressRecord setCityName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>work.address.city_name</code>. 市区町村名
     */
    @Size(max = 191)
    public String getCityName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>work.address.town_street_cd</code>. 大字町丁目コード
     */
    public AddressRecord setTownStreetCd(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>work.address.town_street_cd</code>. 大字町丁目コード
     */
    @NotNull
    @Size(max = 12)
    public String getTownStreetCd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>work.address.town_street_name</code>. 大字町丁目名
     */
    public AddressRecord setTownStreetName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>work.address.town_street_name</code>. 大字町丁目名
     */
    @Size(max = 191)
    public String getTownStreetName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>work.address.latitude</code>. 緯度
     */
    public AddressRecord setLatitude(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>work.address.latitude</code>. 緯度
     */
    public Double getLatitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>work.address.longitude</code>. 経度
     */
    public AddressRecord setLongitude(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>work.address.longitude</code>. 経度
     */
    public Double getLongitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>work.address.origin_doc_cd</code>. 原典資料コード
     */
    public AddressRecord setOriginDocCd(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>work.address.origin_doc_cd</code>. 原典資料コード
     */
    @Size(max = 1)
    public String getOriginDocCd() {
        return (String) get(8);
    }

    /**
     * Setter for <code>work.address.town_street_kbn_cd</code>. 大字・字・丁目区分コード
     */
    public AddressRecord setTownStreetKbnCd(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>work.address.town_street_kbn_cd</code>. 大字・字・丁目区分コード
     */
    @Size(max = 1)
    public String getTownStreetKbnCd() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Double, Double, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Double, Double, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Address.ADDRESS.PREFECTURE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Address.ADDRESS.PREFECTURE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Address.ADDRESS.CITY_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Address.ADDRESS.CITY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Address.ADDRESS.TOWN_STREET_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Address.ADDRESS.TOWN_STREET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Address.ADDRESS.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Address.ADDRESS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Address.ADDRESS.ORIGIN_DOC_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Address.ADDRESS.TOWN_STREET_KBN_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPrefectureCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrefectureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCityCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCityName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTownStreetCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTownStreetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOriginDocCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getTownStreetKbnCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPrefectureCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrefectureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCityCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCityName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTownStreetCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTownStreetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOriginDocCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTownStreetKbnCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value1(String value) {
        setPrefectureCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value2(String value) {
        setPrefectureName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value3(String value) {
        setCityCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value4(String value) {
        setCityName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value5(String value) {
        setTownStreetCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value6(String value) {
        setTownStreetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value7(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value8(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value9(String value) {
        setOriginDocCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value10(String value) {
        setTownStreetKbnCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Double value7, Double value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(String prefectureCd, String prefectureName, String cityCd, String cityName, String townStreetCd, String townStreetName, Double latitude, Double longitude, String originDocCd, String townStreetKbnCd) {
        super(Address.ADDRESS);

        set(0, prefectureCd);
        set(1, prefectureName);
        set(2, cityCd);
        set(3, cityName);
        set(4, townStreetCd);
        set(5, townStreetName);
        set(6, latitude);
        set(7, longitude);
        set(8, originDocCd);
        set(9, townStreetKbnCd);
    }
}
