/*
 * This file is generated by jOOQ.
 */
package com.example.tables.records;


import com.example.tables.Prefecture;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 都道府県
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrefectureRecord extends UpdatableRecordImpl<PrefectureRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -2114739713;

    /**
     * Setter for <code>work.prefecture.prefecture_cd</code>. 都道府県コード
     */
    public PrefectureRecord setPrefectureCd(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>work.prefecture.prefecture_cd</code>. 都道府県コード
     */
    @NotNull
    @Size(max = 2)
    public String getPrefectureCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>work.prefecture.prefecture_name</code>. 都道府県名
     */
    public PrefectureRecord setPrefectureName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>work.prefecture.prefecture_name</code>. 都道府県名
     */
    @Size(max = 191)
    public String getPrefectureName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Prefecture.PREFECTURE.PREFECTURE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Prefecture.PREFECTURE.PREFECTURE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPrefectureCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrefectureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPrefectureCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrefectureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefectureRecord value1(String value) {
        setPrefectureCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefectureRecord value2(String value) {
        setPrefectureName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefectureRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrefectureRecord
     */
    public PrefectureRecord() {
        super(Prefecture.PREFECTURE);
    }

    /**
     * Create a detached, initialised PrefectureRecord
     */
    public PrefectureRecord(String prefectureCd, String prefectureName) {
        super(Prefecture.PREFECTURE);

        set(0, prefectureCd);
        set(1, prefectureName);
    }
}
