/*
 * This file is generated by jOOQ.
 */
package com.example.tables.records;


import com.example.tables.User;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * ユーザ
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<ULong, String, String, UShort, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -260593615;

    /**
     * Setter for <code>work.user.user_id</code>. ユーザid
     */
    public UserRecord setUserId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>work.user.user_id</code>. ユーザid
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>work.user.user_name</code>. ユーザ名
     */
    public UserRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>work.user.user_name</code>. ユーザ名
     */
    @NotNull
    @Size(max = 191)
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>work.user.user_password</code>. パスワード
     */
    public UserRecord setUserPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>work.user.user_password</code>. パスワード
     */
    @NotNull
    @Size(max = 191)
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>work.user.role_cd</code>. 役割コード
     */
    public UserRecord setRoleCd(UShort value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>work.user.role_cd</code>. 役割コード
     */
    @NotNull
    public UShort getRoleCd() {
        return (UShort) get(3);
    }

    /**
     * Setter for <code>work.user.credentials_expired_flg</code>. 権限期限切れフラグ
     */
    public UserRecord setCredentialsExpiredFlg(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>work.user.credentials_expired_flg</code>. 権限期限切れフラグ
     */
    public Boolean getCredentialsExpiredFlg() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>work.user.account_expired_flg</code>. アカウント期限切れフラグ
     */
    public UserRecord setAccountExpiredFlg(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>work.user.account_expired_flg</code>. アカウント期限切れフラグ
     */
    public Boolean getAccountExpiredFlg() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>work.user.account_locked_flg</code>. アカウント停止フラグ
     */
    public UserRecord setAccountLockedFlg(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>work.user.account_locked_flg</code>. アカウント停止フラグ
     */
    public Boolean getAccountLockedFlg() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>work.user.enabled_flg</code>. 有効フラグ
     */
    public UserRecord setEnabledFlg(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>work.user.enabled_flg</code>. 有効フラグ
     */
    public Boolean getEnabledFlg() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>work.user.created_at</code>. 作成日時
     */
    public UserRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>work.user.created_at</code>. 作成日時
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>work.user.updated_at</code>. 更新日時
     */
    public UserRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>work.user.updated_at</code>. 更新日時
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<ULong, String, String, UShort, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<ULong, String, String, UShort, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return User.USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.USER_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field4() {
        return User.USER.ROLE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return User.USER.CREDENTIALS_EXPIRED_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return User.USER.ACCOUNT_EXPIRED_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return User.USER.ACCOUNT_LOCKED_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return User.USER.ENABLED_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return User.USER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component4() {
        return getRoleCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getCredentialsExpiredFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getAccountExpiredFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getAccountLockedFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getEnabledFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value4() {
        return getRoleCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getCredentialsExpiredFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getAccountExpiredFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getAccountLockedFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getEnabledFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(UShort value) {
        setRoleCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(Boolean value) {
        setCredentialsExpiredFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(Boolean value) {
        setAccountExpiredFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Boolean value) {
        setAccountLockedFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(Boolean value) {
        setEnabledFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(ULong value1, String value2, String value3, UShort value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(ULong userId, String userName, String userPassword, UShort roleCd, Boolean credentialsExpiredFlg, Boolean accountExpiredFlg, Boolean accountLockedFlg, Boolean enabledFlg, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(User.USER);

        set(0, userId);
        set(1, userName);
        set(2, userPassword);
        set(3, roleCd);
        set(4, credentialsExpiredFlg);
        set(5, accountExpiredFlg);
        set(6, accountLockedFlg);
        set(7, enabledFlg);
        set(8, createdAt);
        set(9, updatedAt);
    }
}
